#!/bin/bash
# Open Google Play Console pages for completing App Content declarations

PACKAGE="com.iganapolsky.randomtimer"
BASE_URL="https://play.google.com/console/developers/$PACKAGE"

echo "============================================================"
echo "Google Play Console - App Content Setup"
echo "============================================================"
echo ""
echo "Package: $PACKAGE"
echo ""
echo "This script will open all required App Content pages in Chrome."
echo "Complete each page with the exact answers provided below."
echo ""
echo "============================================================"
echo "DECLARATION ANSWERS (keep this terminal visible)"
echo "============================================================"
echo ""
echo "1️⃣  DATA SAFETY:"
echo "   ❌ App does NOT collect or share any user data"
echo "   ❌ No encryption needed (no data collected)"
echo ""
echo "2️⃣  ADVERTISING ID:"
echo "   ❌ No - app does NOT use advertising ID"
echo ""
echo "3️⃣  GOVERNMENT APPS:"
echo "   ❌ No"
echo ""
echo "4️⃣  FINANCIAL FEATURES:"
echo "   ❌ No to all"
echo ""
echo "5️⃣  HEALTH APPS:"
echo "   ❌ No"
echo ""
echo "6️⃣  FOREGROUND SERVICE (FGS) PERMISSIONS:"
echo "   ✅ YES - app uses foreground service"
echo "   📱 Type: Timer / Stopwatch"
echo "   📝 Justification:"
echo "      \"App runs a countdown timer that must continue when the"
echo "       app is in the background to notify the user when time expires.\""
echo ""
echo "7️⃣  EXACT ALARM PERMISSION:"
echo "   ✅ YES - app uses USE_EXACT_ALARM"
echo "   ⏰ Use case: Timer / Alarm"
echo "   📝 Justification:"
echo "      \"App schedules exact alarms to notify the user precisely"
echo "       when their random timer completes.\""
echo ""
echo "============================================================"
echo ""
echo "Opening Play Console in 3 seconds..."
echo "(Keep this terminal visible for reference)"
echo ""
sleep 3

# Open main App Content page
open -a "Google Chrome" "$BASE_URL/app-content"

echo "✅ Opened: App Content Overview"
echo ""
echo "📋 Complete each section in the left sidebar:"
echo "   1. Data safety"
echo "   2. Advertising ID"
echo "   3. Government apps"
echo "   4. Financial features"
echo "   5. Health"
echo "   6. FGS permissions (Foreground Service)"
echo "   7. Exact alarm"
echo ""
echo "After completing all sections, verify Store listing:"
echo "   - Go to: Store listing (left sidebar)"
echo "   - Re-save name/description"
echo "   - Verify screenshots are showing"
echo ""
echo "Then set up Closed Testing (REQUIRED for 2026):"
echo "   - Go to: Testing → Closed testing"
echo "   - Create closed testing track"
echo "   - Upload AAB: app/build/outputs/bundle/release/app-release.aab"
echo "   - Add 20+ testers"
echo "   - Run for 14+ days before production access"
echo ""
echo "============================================================"
echo "Keep this terminal open for reference!"
echo "============================================================"
