# GitGuardian Configuration
# This file configures GitGuardian Shield for secret detection

# Paths to scan
paths-ignore:
  - "node_modules/**"
  - ".git/**"
  - "coverage/**"
  - "android/**"
  - "ios/**"
  - "*.log"
  - "*.lock"
  - "yarn.lock"
  - "package-lock.json"

# File patterns to ignore
ignore:
  - "*.md"
  - "*.txt"
  - "*.json"
  - "*.yml"
  - "*.yaml"
  - "*.lock"

# Secret patterns to ignore (false positives)
ignore-secrets:
  - "passwordGenerator"  # Our password generator function
  - "PasswordOptions"    # Our password options type
  - "generatePassword"   # Our password generation function
  - "calculatePasswordStrength"  # Our password strength function

# Minimum secret length
min-secret-length: 8

# Exit codes
exit-zero: false  # Fail on secrets found

# Verbose output
verbose: true

# Show secrets in output (for debugging)
show-secrets: false
