#!/bin/bash

# Daily Automation Script using Cursor Headless
# Runs your entire development workflow AUTOMATICALLY
# Cost: $0 (runs locally)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="$SCRIPT_DIR/../.cursor-logs/daily-$(date +%Y%m%d).log"

echo "🚀 Starting Daily Automation - $(date)" | tee -a "$LOG_FILE"

# 1. Morning standup
echo "📊 Generating standup..." | tee -a "$LOG_FILE"
"$SCRIPT_DIR/cursor-agent-orchestrator.sh" --standup >> "$LOG_FILE" 2>&1

# 2. Process GitHub issues into tasks
echo "📋 Processing issues..." | tee -a "$LOG_FILE"
gh issue list --state open --limit 5 --json number,title,body | \
    jq -r '.[] | "sp-\(.number % 3 + 1):\(.title)"' > \
    "$SCRIPT_DIR/../.cursor-tasks/batch-tasks.txt"

# 3. Run parallel agents on tasks
echo "🤖 Running parallel agents..." | tee -a "$LOG_FILE"
"$SCRIPT_DIR/cursor-agent-orchestrator.sh" --parallel >> "$LOG_FILE" 2>&1

# 4. Generate tests
echo "🧪 Generating tests..." | tee -a "$LOG_FILE"
for worktree in sp-biometrics sp-secure-storage sp-ai-intelligence; do
    if [ -d "/Users/igorganapolsky/workspace/git/apps/$worktree" ]; then
        cd "/Users/igorganapolsky/workspace/git/apps/$worktree"
        cursor-agent --print --force "Generate unit tests for recent changes" >> "$LOG_FILE" 2>&1
    fi
done

# 5. Run code review
echo "🔍 Running code review..." | tee -a "$LOG_FILE"
"$SCRIPT_DIR/cursor-agent-orchestrator.sh" --review >> "$LOG_FILE" 2>&1

# 6. Create PRs for completed work
echo "🔀 Creating PRs..." | tee -a "$LOG_FILE"
for worktree in sp-biometrics sp-secure-storage sp-ai-intelligence; do
    if [ -d "/Users/igorganapolsky/workspace/git/apps/$worktree" ]; then
        cd "/Users/igorganapolsky/workspace/git/apps/$worktree"
        if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "feat: automated improvements via Cursor headless" || true
        fi
        
        if [ -n "$(git log origin/develop..HEAD 2>/dev/null)" ]; then
            branch=$(git branch --show-current)
            gh pr create \
                --title "🤖 Automated: $branch improvements" \
                --body "Generated by Cursor headless automation" \
                --base develop \
                --head "$branch" || true
        fi
    fi
done

echo "✅ Daily automation complete - $(date)" | tee -a "$LOG_FILE"
echo "📊 Summary saved to: $LOG_FILE"
